---
name: "Feature Branch"
on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
      - "!main" # excludes branch main
      - "!gh-pages" #exclude

jobs:
  test-policies:
    runs-on: ubuntu-latest
    steps:
      # Checking out source codes
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: OPA test
        uses: petroprotsakh/opa-test-action@v2.1
        with:
          tests: "charts/*/opa"
          options: "-v"
      - name: OPA Test coverage
        uses: petroprotsakh/opa-test-action@v2.1
        with:
          tests: "charts/*/opa"
          options: "-c"
